"""
Convert trained .weights.h5 model to TensorFlow Lite for STM32 deployment
Includes INT8 quantization for size reduction
"""

import tensorflow as tf
import numpy as np
import os

print("\n" + "="*80)
print("TensorFlow Lite Conversion for STM32 Deployment")
print("="*80)

from net.ChronoNet import net
from net.DL_config import Config

def convert_model_to_tflite(weights_path, config, output_path='seizure_model.tflite'):
    """
    Convert .weights.h5 to .tflite with INT8 quantization
    
    Args:
        weights_path: Path to .weights.h5 file
        config: Config object used during training
        output_path: Output .tflite file path
    """
    
    print(f"\n[INFO] Loading model architecture...")
    print(f"  Model: {config.model}")
    print(f"  Channels: {config.CH}")
    print(f"  Input shape: ({config.frame * config.fs}, {config.CH})")
    
    # Recreate model architecture
    model = net(config)
    
    # Load trained weights
    print(f"\n[INFO] Loading weights from: {weights_path}")
    model.load_weights(weights_path)
    
    print(f"[SUCCESS] Model loaded successfully")
    model.summary()
    
    # Create converter
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    
    # Enable optimizations
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    
    # Representative dataset for quantization calibration
    def representative_dataset():
        print("\n[INFO] Generating representative dataset for quantization...")
        for i in range(100):
            # Generate random samples matching input shape
            # Use realistic EEG/ECG/EMG value ranges
            data = np.random.randn(1, int(config.frame * config.fs), config.CH).astype(np.float32)
            # Normalize to typical biosignal range
            data = data * 50.0  # Typical EEG/ECG/EMG amplitude in microvolts
            yield [data]
        print("[INFO] Representative dataset generated (100 samples)")
    
    converter.representative_dataset = representative_dataset
    
    # Set quantization specs
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    
    print("\n[INFO] Converting to TensorFlow Lite with INT8 quantization...")
    print("[INFO] This may take 1-2 minutes...")
    
    try:
        tflite_model = converter.convert()
    except Exception as e:
        print(f"[WARNING] INT8 quantization failed: {e}")
        print("[INFO] Falling back to float32 model...")
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        tflite_model = converter.convert()
    
    # Save TFLite model
    with open(output_path, 'wb') as f:
        f.write(tflite_model)
    
    model_size_kb = len(tflite_model) / 1024
    print(f"\n[SUCCESS] TFLite model saved: {output_path}")
    print(f"[SUCCESS] Model size: {model_size_kb:.2f} KB")
    
    # Check STM32 compatibility
    if model_size_kb < 1024:  # 1 MB
        print(f"[SUCCESS] Fits on STM32F746 (1 MB Flash)! ✓")
    else:
        print(f"[WARNING] Model may be too large for STM32F746")
        print(f"[INFO] Consider further optimization or use STM32H7 series")
    
    return tflite_model

def generate_c_header(tflite_model, output_path='model_data.h'):
    """
    Generate C header file with model data array
    
    Args:
        tflite_model: TFLite model bytes
        output_path: Output .h file path
    """
    print(f"\n[INFO] Generating C header file: {output_path}")
    
    with open(output_path, 'w') as f:
        f.write("/*\n")
        f.write(" * model_data.h\n")
        f.write(" * Auto-generated TFLite model data for STM32\n")
        f.write(" * Generated by convert_to_tflite.py\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_DATA_H\n")
        f.write("#define MODEL_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        
        # Write model array
        f.write(f"const unsigned int seizure_model_tflite_len = {len(tflite_model)};\n")
        f.write("const unsigned char seizure_model_tflite[] = {\n")
        
        # Write in rows of 12 bytes for readability
        for i in range(0, len(tflite_model), 12):
            row = tflite_model[i:min(i+12, len(tflite_model))]
            hex_values = ', '.join(f'0x{b:02x}' for b in row)
            f.write(f"  {hex_values}")
            if i + 12 < len(tflite_model):
                f.write(",\n")
            else:
                f.write("\n")
        
        f.write("};\n\n")
        f.write("#endif // MODEL_DATA_H\n")
    
    print(f"[SUCCESS] C header file generated: {output_path}")
    print(f"[INFO] Include this file in your STM32 project")

def main():
    # Configuration - match your training config!
    
    # For multi-modal model (4 channels)
    config = Config(
        fs=256,
        CH=4,  # 4 channels: EEG(2) + ECG(1) + EMG(1)
        model='ChronoNet',
        num_classes=3,
        frame=4,  # Match training config
        dropoutRate=0.3
    )
    
    # Path to trained weights
    model_name = config.get_name()
    weights_path = os.path.join('net', 'save_dir', 'models', model_name, 'Weights', f'{model_name}.weights.h5')
    
    if not os.path.exists(weights_path):
        print(f"[ERROR] Weights not found: {weights_path}")
        print(f"[INFO] Make sure training has completed successfully")
        return
    
    print(f"[INFO] Converting model: {model_name}")
    
    # Convert to TFLite
    tflite_model = convert_model_to_tflite(weights_path, config)
    
    # Generate C header
    generate_c_header(tflite_model)
    
    print("\n" + "="*80)
    print("CONVERSION COMPLETE!")
    print("="*80)
    print("\n[NEXT STEPS]")
    print("1. Copy 'seizure_model.tflite' and 'model_data.h' to your STM32 project")
    print("2. Include TensorFlow Lite Micro library")
    print("3. Use the C code from STM32_DEPLOYMENT_GUIDE.md")
    print("4. Build and flash to STM32 Nucleo")
    print("\n[FILES CREATED]")
    print("  - seizure_model.tflite (quantized model)")
    print("  - model_data.h (C header with model array)")
    print("="*80)

if __name__ == "__main__":
    main()

